# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-auth0-app
  description: Auth0 Application component
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component

